### ISSUE TITLE
Config options for grid width & cursor size

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warp#12]
It'd be helpful to make these config options:

```
#define CURSOR_WIDTH 15
#define BORDER_WIDTH 5
#define GRID_LINE_WIDTH 2
```

Would like to try making them smaller - sometimes I can't tell exactly where I'm clicking, and the borders/grid get smushed up when zoomed all the way in

**Comment by rvaiya** [comment]
Done, see the man page.
