### ISSUE TITLE
human readable format of history file

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warp#140]
This is essentially only relevant when hint mode with configurable coordinate sets gets implemented and should stay here  as a reminder until the decision has been taken: 

Assuming the above feature gets implemented, the configurable coordinate sets should be saved in some simple human readable format which the history file should use as well. This way, it would also be trivial to build a coordinate set by simply copying (parts of) an appropriate history file.

**Comment by rvaiya** [comment]
>  when hint mode with configurable coordinate sets gets implemented 

This is now implemented in the form of `--query`.

> Assuming the above feature gets implemented, the configurable coordinate sets should be saved in some simple human readable format which the history file should use as well.

I don't agree with this. The history file is for warpd's internal use only (akin to vim swap files). The fact that it is not human readable is a feature, not a bug.

> This way, it would also be trivial to build a coordinate set by simply copying (parts of) an appropriate history file.

I've introduced a 'print' key which should make it fairly trivial to generate files which can be consumed by `--query`.
