### ISSUE TITLE
[feature request] optional history recording for oneshot modes

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warp#141]
This is a continuation of the discussion in #111 (localized hint mode).

### setup and usage report

I have been using quadrant hint mode via the `--query` option (called by keyd via `command()`). Actually, for me it is much more efficient than using both plain hint mode and also two-step hint mode, and I'm sure that other people will have the same experience. Again, for reference in case others read this, here is the functionality:

I've bound a “modifier” (caps lock and tab)  plus one of five keys under my right hand (j, k, i, o, l on QWERTY to be precise) to start hint mode localized to one of the four quadrants of the screen or the center of the screen. Center here means cutting off 25% of total width on top, bottom, left and right, a quadrant extends 60% of total width and length, starting from one of the four corners of the screen (so that there is some overlap with the other quadrants, preventing one to think about which quadrant to choose for points of interest near the corner). I did the same with another modifier, which automatically clicks after selection. Due to the power of keyd, both modifiers serve a double functionality depending on whether they are held or tapped, so that there is no loss of tab key functionality. (caps lock is completely repurposed as usual to activate a keyd layer). Starting hint mode localized means calling warpd using the `--query` option with a predefined hint set fed into it by an external script via keyd's `command()` functionality.

For my resolution, this has eliminated the need to do any pointer adjustments after choosing a hint in at least 95% of use cases (the other 5% typically require such precise pointer movements that normal mode or an external mouse is necessary anyway), while at the same time slightly reducing the length of `hint_chars`. For me, this is now the holy grail of pointer movement.

### actual feature request

Selections done via the above functionality are not recorded into history. I'm actually missing this functionality quite a lot as I have another hotkey to start warpd's history mode, which is very useful for webforms, gui applications etc. where you often have to click the same spot repeatedly. It would be nice if there was an option to record to history in any of the oneshot modes (not only `--query`, but also `--hint`, `--hint2`, `--normal` and `--grid`, with the latter four only recording after a click of course). I realize that this would require keyd to read/write the history file much more frequently, but given the usefulness of this feature it's a reasonable price to pay. Alternatively, one could think about implementing some sort of IPC functionality, so that keyd in oneshot mode could first try to tell a running keyd instance to record to history before writing to the history file, or even start the requested mode directly from the running instance.

**Comment by rvaiya** [comment]
> Currently, the behaviour is not consistent, as --query exits immediately, while the other modes always enter normal mode after selection.

This is by design, as it allows `--query` to be used by scripts which may just want to query a set of coordinates. 

If the user wishes to enter a mode after selecting a hint it is trivial to bold on another invocation with the desired mode flag.

E.G: 

`warpd --query < hints ; warpd --normal`.


> simply exit after selection and indicate via the exit code whether warping was cancelled. Then a wrapper script can decide independently what to do next, for example starting keyd --normal if normal mode is desired or do some clicking.

The 'oneshot' flags are intended to be used to launch warpd in a daemonless way, but still facilitate a full movement session. This was originally intended for wayland users, but is incidentally useful for scripting. In retrospect, 'oneshot' was probably a bad name.

The latest commit will use the oneshot button used to terminate warpd as the exit code. Paired with '-c' it should be possible to achieved what you want.

> To enable history recording for scripts, one could add --click-left and --click-right options, which make warpd click, record to history and exit immediately.

+1. I will add this shortly.

> This level of scriptability would also make the previsioned keyd merge obsolete from a functional point of view, as everything could then be achieved via scripts called by keyd's command() action.

It would still have some advantages (particularly on wayland). Though it is currently on the backburner. 'merge' is probably the wrong word, as it will most likely end up being a separate implementation consisting of a subsets of warpd's most useful features.

**Comment by rvaiya** [comment]
With respect to your second request my original suggestion was to pass in a set of custom oneshot bindings using `-c` but that doesn't cover all modes and can be quite cumbersome. 

After some reflection I've added some additional flags which should allow you to do most of what you have described in this issue. They should be available in the latest commit.
