### ISSUE TITLE
transparency of foreground and background colors for hints

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warp#143]
I just wanted to test a completely transparent hint background (so that only the labels are shown) but when specifying alpha values for `hint_{fg,bg}color`, it seems as if the value for the background color is applied to the foreground color as well, i.e. setting `hint_bgcolor = #00000000` and `hint_fgcolor = #ffffffff` has the effect of drawing completely invisible hints. Is this intended behaviour?

**Comment by rvaiya** [comment]
This is a known bug in the X implementation. Opacity is achieved by setting `_NET_WM_WINDOW_OPACITY` which affects the entire window. Short of grabbing screen content and doing alpha compositing in warpd (expensive), I'm not aware of a better way to achieve this.

**Comment by rvaiya** [comment]
The rectangle is part of the window. warpd uses the X11 shape extension in conjunction with the cached output of Xft drawing routines in a buffer which gets copied when the window is displayed. In theory it should be possible to use the shape extension to just crop out the drawn fonts but I don't know if this is possible/performant from memory and it wouldn't be worth the time investment.
