### ISSUE TITLE
feature request: oneshot support for drag mode

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warp#146]
It would be nice to add the ability of starting keyd directly in drag mode (entering drag mode is the only warpd functionality not scriptable at the moment), so that combined with `--oneshot`, warpd exits when either the copy or drag key or any mouse button is pressed, while just using the drag mode flag on its own is a convenience feature and combines `--normal` with the drag mode activation keypress. For consistency, pointer coordinates upon exit could be printed, together with the mouse button pressed (either as a third field, or via exit status).

Background:

I still haven't become completely independent of the trackpoint. Therefore, it regularly happens that I'm on some webpage with the pointer already at the correct position and would like to select some text. This requires first activating warpd and then entering drag mode. In order to save keypresses, I have a keyd macro for this, which first presses the activation key sequence, waits a bit and then presses the key to start drag mode. Now I would like to use the dragging operation in a script, to automate processing of the selected text. Of course, I could probably simulate the needed keypresses to activate normal mode and then enter drag mode by some command inside the script, but there is no way for the script to know if the selection was successful or not or is still active (when you exit with a left mouse click, the selection often disappears). With the above feature, the script could first check whether warpd exited cleanly (so some selection was made) and then use the third output field to infer where that selection is (probably gone if a mouse key was pressed and probably still selected if copy or drag key was pressed, i.e. no third output field present).

**Comment by rvaiya** [comment]
I've added this to the latest commit.
