### ISSUE TITLE
feature request: print pointer coordinates independently of --oneshot

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warp#147]
Another thing which just came up while writing some scripts (also related to  #144):

When calling warpd with any of the mode flags, I think that it would make sense to always print pointer coordinates and eventual button presses to stdout upon regular exit. The additional effect of `--oneshot` would then purely be that non-normal modes exit immediately after selection instead of dropping to normal mode.

This is sometimes advantageous to calling warpd twice (first with `--oneshot` and after exit with `--normal`), as the script can't know in advance if the second call is necessary or not.

In particular, there would be no difference in behaviour between `warpd --normal` and `warpd --oneshot --normal`.

PS: Sorry for the plethora of feature requests today, it simply all came up within a short amount of time.

**Comment by rvaiya** [comment]
I've added the key used for printing, this should allow you to do something like this

```
echo ''print: z p|warpd -c - --normal | while read x y action; do 
	case $action in
		z) echo "executing z action on $x $y" ;;
		p) echo "executing p action on $x $y" ;;
	esac
done
```
