### ISSUE TITLE
allow compact form of multiple mouse button keybindings?

### ISSUE THREAD

**Issue by herrsimon** [rvaiya/warp#153]
When writing the keybinding examples, I stumpled upon the unnatural discrepancy that `buttons` and `oneshot_buttons` to not accept multiple space separated values (triples of keys in this case), in contrast to options which expect a single key. Do you agree that it should be allowed to write `buttons = a o u , . p` instead of two separate rows? This could easily be achieved by replacing `btn` with `(btn - 1) % 3 + 1` at the right places.

**Comment by rvaiya** [comment]
I think it is better to leave things as is. This is predicated on the assumption that there are precisely 3 buttons, which is an implementation detail subject to change. It is also a bit harder to read. 

warpd has many warts which are a byproduct of its development history. I would probably make different decisions if I was designing the config logic from scratch.
