### ISSUE TITLE
100% cpu usage with compositors.

### ISSUE THREAD

**Issue by matheusfillipe** [rvaiya/warp#16]
Kudos for the great work so far! This is my favorite small project!

Everything is working fine when using a twm. Everything works fine when having the compositor disabled. If i launch warp with the compositor enabled it starts using 100% of the cpu. I actually see "warp -d" and "/usr/lib/Xorg using 100% cpu. 

But I found a trick. Disabling the compositor, launching warp and re-enabling the compositor seems to help but is kinda random sometimes.

I am having this issue inside KDE. I know having this working on a DE isn't the main point here but... would be just nice and why not. 
If you need any help for testing I'll be here!

**Comment by rvaiya** [comment]
Thanks :). I believe the bug that was causing this has been fixed in the latest commit. I will leave it to you confirm and close the issue.

**Comment by matheusfillipe** [comment]
It is fixed! Great job!
