### ISSUE TITLE
More documentation for config and usage

### ISSUE THREAD

**Issue by robrecord** [rvaiya/warp#271]
I can't find anywhere a complete reference for the config file, or a list of all the keys. For example there is supposedly a scroll feature but it is not documented.

How do I go about discovering these please?

**Comment by CT-66** [comment]
`warpd --list-options` contains most of the documentation

**Comment by robrecord** [comment]
Thanks This needs to be surfaced somewhere for other users. 
Here's my README edit: https://github.com/rvaiya/warpd/pull/274
