### ISSUE TITLE
Add an cmd option `--restart`

### ISSUE THREAD

**Issue by LintaoAmons** [rvaiya/warp#284]
Sometimes, I found after disconnected from a monitor or changed the orrangement of the displays, warpd can't adjust itself correctly which requires a restart of the process.

I'm currently using `htop` to find the existing process and to kill it, then restart the warpd process again which is quite cumbersome.

So if we could have some command line option like `--restart` should be quite helpful!

**Comment by Hi-Angel** [comment]
I am not sure there's a point in reimplementing what's already provided by system service manager.

If by any chance you're using systemd, [there's a PR implementing systemd service](https://github.com/rvaiya/warpd/pull/309), till it's merged you can just copy the service to your system and use `systemctl daemon-reload --user`, and then manage warpd as the usual service.

**Comment by Hi-Angel** [comment]
> …and then manage warpd as the usual service

…so the functional you want in this case would be provided by `systemctl restart --user warpd`.

**Comment by sfc-gh-jroes** [comment]
What's the standard way to restart on osx?

**Comment by sfc-gh-jroes** [comment]
Answering my own question, this worked for me:

```
➜  ~ launchctl list | grep warp
1001    0       com.warpd.warpd
➜  ~ launchctl kickstart -k com.warpd.warpd
Unrecognized target specifier, did you mean
gui/501/com.warpd.warpd

Usage: launchctl kickstart [-k] [-p] <service-target>
        -k      Terminates the service if it is already running.
        -p      Prints the PID of the service that was started.
        -s      Starts the service suspended so that a debugger may attach.
<service-target> takes a form of <domain-target>/<service-id>.
Please refer to `man launchctl` for explanation of the <domain-target> specifiers.
➜  ~ launchctl kickstart -k gui/501/com.warpd.warpd
```
