### ISSUE TITLE
Feature Request: option to exit warp mode on a click

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warp#4]
It'd be useful to exit warp mode after a click, not just with the 'exit' key. This is how keyboardio works.

Might be nice to make the exit keysym configurable as well

**Comment by rvaiya** [comment]
Done. The key after the third mouse button (passed to -k) is now interpreted as a close key. You can make this the same as button 1 to achieve the effect you want.

**Comment by rvaiya** [comment]
This is now the default behaviour. A small timeout is used to facilitate double/triple clicking.
