### ISSUE TITLE
Using same keysym for activation & warping causes problems

### ISSUE THREAD

**Issue by wearpants** [rvaiya/warp#7]
If I have a config that uses the same base keysym for activation & warping, the program treats it as if I had warped already when it starts:

```
grid_keys: Tab,space,Up,Right
activation_key: A-space
```
In other words, it acts as if I pressed `A-space space` when I press `A-space`

**Comment by rvaiya** [comment]
The 'trigger_mods' feature was interfering with the overlapping mappings. I have added an additional check to fix this. I believe you were the one that originally requested the ability to immediately warp to a screen segment (previously 'always_active' mode) so you may want to look at the trigger_mods option.
