### ISSUE TITLE
Default keybindings

### ISSUE THREAD

**Issue by Enzime** [rvaiya/warp#70]
I think that the default bindings and the default modes should start with the same letter to make them easier to remember, like changing hint to `A-M-h`.

As a vim user, just from the name my expectation is that normal mode would be the default mode (more like what you get when you press `esc`). I think it would be a good idea to rename it to `cursor mode` or something similar which would bring it inline with the `A-S-c` binding.

It would also be nice to change the default buttons from `m, comma, .` to something used by the left hand so that you can keep your right hand on `hjkl`.

**Comment by rvaiya** [comment]
`A-M-c` and `A-M-g` were originally chosen for their mnemonics, but I'm not sure what possessed me to pick `A-M-x` for hint mode. I think it may have had something to do with binding conflicts at the time. I would be willing to consider changing it, but at this point there are enough users who have probably memorized the default bindings that it would probably cause confusion. They can always be modified in `~/.config/warpd/config` if desired.

> It would also be nice to change the default buttons from m, comma, . to something used by the left hand so that you can keep your right hand on hjkl.

These were more carefully chosen. `m`, `,` and `.` can be reached by sliding your fingers down one row, and they closely mirror their positions on a mouse. In addition to this, I wasn't sure whether or not I might end up using `a`, `s`, `d`, `f` for their mnemonic values or vi resonance (and they may still be used at some point). A good case can probably be made more moving them, but I am loath to make too many changes to the defaults at this point. The enterprising user is expected to make good use of the man page anyway ;).

**Comment by ChrispyChris** [comment]
I have to say I agree with your vision currently @rvaiya. Also stoked to have found this through Reddit. I'm hoping I can find some "somewhat" beginner projects to work on with this. I'm not a pro at C but think I could look up enough to maybe help contribute :)? Let me know if you have any ideas, I'm also polling through the issues to see if anything pops out.

**Comment by rvaiya** [comment]
@ChrispyChris 
 
I appreciate the offer :). The best way to contribute is to file an issue if you find any bugs or notice any deficiencies in the documentation. Distribution packaging is also welcome. 

You are, of course, also free to study the source, but should be aware that it is probably not terribly beginner friendly. Much of the code involves abusing various (often undocumented) platform specific APIs to accomplish warpd's goals, though I've tried to abstract most of the ugliness away to make the higher level logic tractable.

If you do feel you are in a position to contribute to the code, I would only ask that you file an issue discussing the intended changes before submitting a PR containing any major changes to ensure the proposals align with the project goals and don't conflict with anything currently sitting in my tree.

**Comment by rvaiya** [comment]
I'm closing this for now. Feel free to open another issue if you have any other concerns.
